
IF
	OR(3)
		Global("KorganMazzy","GLOBAL",18)
		Global("KorganMazzy","GLOBAL",20)
		Global("KorganMazzy","GLOBAL",30)
	See("Korgan")
	!StateCheck("Korgan",STATE_SLEEPING)
	InParty("Korgan")
THEN
	RESPONSE #100
		Interact("Korgan")
END

IF
	OR(2)
		Global("KorganMazzy","GLOBAL",17)
		Global("KorganMazzy","GLOBAL",19)
	RealGlobalTimerExpired("KorgMaz","GLOBAL")
THEN
	RESPONSE #100
		IncrementGlobal("KorganMazzy","GLOBAL",1)
END